### ISSUE TITLE
Getting error while executing Wallet Transfer 

### ISSUE THREAD

**Issue by sir-argupta** [ivangfr/ethereum-springboot-react#1]
Hey,
I was executing the **api/wallets/transfer** Method with these Parameters on Kovan Testnet
`curl -X 'POST' \
  'http://localhost:8080/api/wallets/transfer' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "fromAddress": "0x41FFF7047D2cc32f2b1bb945a503B8A3A623C1c5",
  "toAddress": "0x549c553fECD3f8280ba915E98288b94fE8356974",
  "amount": 100005814145695790,
  "gasPrice": 1,
  "gasLimit": 3000000
}'`

But it failed with following errors 

`{
  "timestamp": "2022-03-26T20:11:25.689+00:00",
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.web3j.exceptions.MessageDecodingException",
  "message": "Value must be in format 0x[1-9]+[0-9]* or 0x0",
  "path": "/api/wallets/transfer"
}`
Can you please help me with this..!?

**Comment by ivangfr** [comment]
Hi @sir-argupta Unfortunately, I don't have experience with Kovan Testnet. My project is using a local Ethereum blockchain that is running as a Docker container.

**Comment by sir-argupta** [comment]
hi @ivangfr 
Thanks
